### ISSUE TITLE
Helm chart or how-to of deploying to k8s

### ISSUE THREAD

**Issue by korjavin** [grafana/kubernetes-diff-logger#6]
It would be very useful to have ready to use instruction about deploy.

**Comment by joe-elliott** [comment]
A helm chart feels a bit like overkill for this project.  I have added example yaml in #7.  Do you feel like this sufficient?

**Comment by korjavin** [comment]
Looks good.

Funny enough I made exactly the same yesterday

https://github.com/korjavin/k8s-kubernetes-diff-logger
